/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-05-25 06:10:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import function.Me;

public final class crypto_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("function.Me");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String saysomething = "", other = "";
	HttpSession ses = request.getSession(false);

	if(ses != null) {
		if(Me.compareCookies_Request_Session(Me.brownie, request, ses)) {
				if(Me.compareCookies_Request_Session(Me.idAuth, request, ses)) {
					Cookie newBrownie = Me.bakeBrownie(Integer.MAX_VALUE), brownie = Me.findCookie(Me.brownie, request);
					Cookie auth = Me.findCookie(Me.idAuth, request), newAuth = Me.idAuthGen(Integer.MAX_VALUE);

					saysomething = String.format("your [%s] cookie %s is now %s", brownie.getName(), brownie.getValue(), newBrownie.getValue());
					other = String.format("your [%s] cookie %s is now %s", auth.getName(), auth.getValue(), newAuth.getValue());

					brownie.setMaxAge(0);
					brownie.setValue(null);
					auth.setMaxAge(0);
					auth.setValue(null);

					response.addCookie(newBrownie);
					response.addCookie(newAuth);

					ses.setAttribute(Me.brownie, newBrownie);
					ses.setAttribute(Me.idAuth, newAuth);
				}
				else {
					System.out.println("d");
					response.sendRedirect(Me.errorHtml);
				}
		}
		else {
			System.out.println("e");
			response.sendRedirect(Me.errorHtml);
		}
	}
	else {
		System.out.println("f");
		response.sendRedirect(Me.errorHtml);
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>Daniel website</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/projects.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style_2.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <nav>\r\n");
      out.write("        <button type=\"button\" id=\"toggle-btn\">\r\n");
      out.write("            <i class=\"fa fa-bars\"></i>\r\n");
      out.write("        </button>\r\n");
      out.write("        <span>Menú</span>\r\n");
      out.write("        <ul class=\"sidebar__menu\">\r\n");
      out.write("            <li><a href=\"#\"><i class=\"fa fa-home\"></i>Inicio</a></li>\r\n");
      out.write("            <li><a href=\"#\"><i class=\"fa-sharp fa-solid fa-clock\"></i>Práctica 0</a></li>\r\n");
      out.write("            <li><a href=\"#\"><i class=\"fa-sharp fa-solid fa-clock\"></i>Práctica 1</a></li>\r\n");
      out.write("            <li><a href=\"#\"><i class=\"fa-sharp fa-solid fa-clock\"></i>Práctica 2</a></li>\r\n");
      out.write("            <li><a href=\"#\"><i class=\"fa-sharp fa-solid fa-clock\"></i>Práctica 3</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <header>\r\n");
      out.write("            <h1 class=\"section-heading\">Chismesito crypto - Algoritmo Rijndael</h1>\r\n");
      out.write("        </header>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"tab-container\">\r\n");
      out.write("            <div class=\"tab-filter-container\">\r\n");
      out.write("                <li class=\"filter-btn active\" data-tab=\"web-design\">\r\n");
      out.write("                    <ion-icon name=\"desktop-outline\"></ion-icon>\r\n");
      out.write("                    Historia\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"filter-btn\" data-tab=\"web-development\">\r\n");
      out.write("                    <ion-icon name=\"logo-nodejs\"></ion-icon>\r\n");
      out.write("                    Ventajas\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"filter-btn\" data-tab=\"ux-design\">\r\n");
      out.write("                    <ion-icon name=\"diamond-outline\"></ion-icon>\r\n");
      out.write("                    Aplicaciones\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"filter-btn\" data-tab=\"app-development\">\r\n");
      out.write("                    <ion-icon name=\"logo-google-playstore\"></ion-icon>\r\n");
      out.write("                    Dato extra\r\n");
      out.write("                </li>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"tab-filter-item-container\">\r\n");
      out.write("                <div class=\"tab-item web-design select_tab\">\r\n");
      out.write("                    <div class=\"tab-content-left\">\r\n");
      out.write("                        <img src=\"images/resources/profile.png\" alt=\"web design\" class=\"tab-img\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"tab-content-right\">\r\n");
      out.write("                        <h1 class=\"tab-heading\">Algoritmo</h1>\r\n");
      out.write("                        <p class=\"paragraph\">\r\n");
      out.write("                            De cifrado simétrico desarrollado por Joan Daemen y Vincent Rijmen. \r\n");
      out.write("                            Fue seleccionado como el algoritmo AES (Advanced Encryption Standard) en 2001. \r\n");
      out.write("                            Rijndael se caracteriza por ser seguro, eficiente y versátil.\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <a href=\"#!\" class=\"btn-primary\">Leer más</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"tab-item web-development\">\r\n");
      out.write("                    <div class=\"tab-content-left\">\r\n");
      out.write("                        <h1 class=\"tab-heading\">Proporciona</h1>\r\n");
      out.write("                        <p class=\"paragraph\">\r\n");
      out.write("                            La capacidad de procesar diferentes tamaños de bloques y claves, lo que permite adaptarse a \r\n");
      out.write("                            diversos escenarios de aplicación. Además, ofrece una resistencia significativa a \r\n");
      out.write("                            diversos tipos de ataques criptográficos, incluyendo criptoanálisis diferencial y lineal.\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <a href=\"#!\" class=\"btn-primary\">Leer más</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"tab-content-right\">\r\n");
      out.write("                        <img src=\"images/resources/shiba_1.png\" alt=\"web development\" class=\"tab-img\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"tab-item ux-design\">\r\n");
      out.write("                    <div class=\"tab-content-left\">\r\n");
      out.write("                        <img src=\"images/resources/shiba_2.png\" alt=\"UI/UX Design\" class=\"tab-img\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"tab-content-right\">\r\n");
      out.write("                        <h1 class=\"tab-heading\">Sabías que...</h1>\r\n");
      out.write("                        <p class=\"paragraph\">\r\n");
      out.write("                            Rijndael se ha utilizado en una amplia gama de aplicaciones del mundo real, como la \r\n");
      out.write("                            protección de datos confidenciales en sistemas de comunicación seguros, la encriptación \r\n");
      out.write("                            de archivos y discos, y la seguridad de transmisiones de datos por Internet.\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <a href=\"#!\" class=\"btn-primary\">Leer más</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"tab-item app-development\">\r\n");
      out.write("                    <div class=\"tab-content-left\">\r\n");
      out.write("                        <h1 class=\"tab-heading\">Para saber más..</h1>\r\n");
      out.write("                        <p class=\"paragraph\">\r\n");
      out.write("                            Rijndael recibió su nombre en honor al Castillo de Rijndael, ubicado en \r\n");
      out.write("                            Bélgica, donde Daemen vivió durante el desarrollo del algoritmo.\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <a href=\"#!\" class=\"btn-primary\">Leer más</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"tab-content-right\">\r\n");
      out.write("                        <img src=\"images/resources/shiba_3.png\" alt=\"UI/UX Design\" class=\"tab-img\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script type=\"module\" src=\"https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js\"></script>\r\n");
      out.write("    <script nomodule src=\"https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        let filter_btn = document.querySelectorAll('.filter-btn');\r\n");
      out.write("        let tab_items = document.querySelectorAll('.tab-item');\r\n");
      out.write("\r\n");
      out.write("        for (let i = 0; i < filter_btn.length; i++) {\r\n");
      out.write("            filter_btn[i].addEventListener('click', function () {\r\n");
      out.write("                for (let j = 0; j < filter_btn.length; j++) {\r\n");
      out.write("                    filter_btn[j].classList.remove('active');\r\n");
      out.write("                }\r\n");
      out.write("                let select_tab = filter_btn[i].getAttribute('data-tab');\r\n");
      out.write("                filter_btn[i].classList.add('active');\r\n");
      out.write("                for (let t = 0; t < tab_items.length; t++) {\r\n");
      out.write("                    document.querySelector('.tab-filter-item-container').style.height =\r\n");
      out.write("                        tab_items[t].scrollHeight + 'px';\r\n");
      out.write("                    if (tab_items[t].classList.contains(select_tab)) {\r\n");
      out.write("                        tab_items[t].classList.add('select_tab');\r\n");
      out.write("                    } else {\r\n");
      out.write("                        tab_items[t].classList.remove('select_tab');\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        for (let th = 0; th < tab_items.length; th++) {\r\n");
      out.write("            document.querySelector('.tab-filter-item-container').style.height =\r\n");
      out.write("                tab_items[th].scrollHeight + 'px';\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("    <script>\r\n");
      out.write("        const nav = document.querySelector('nav');\r\n");
      out.write("        const toggle_btn = document.getElementById('toggle-btn');\r\n");
      out.write("\r\n");
      out.write("        toggle_btn.onclick = function () {\r\n");
      out.write("            nav.classList.toggle('hide');\r\n");
      out.write("            this.contentEditable.classList.toggle('expand');\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
