/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-05-25 06:03:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import function.Me;

public final class HomeGrimeTraceBulginessBroilerExpandCrumpetChemicalsObsessiveEffects_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("function.Me");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

	String saysomething = "", other = "";
	HttpSession ses = request.getSession(false);

	if(ses != null) {
		if(Me.compareCookies_Request_Session(Me.brownie, request, ses)) {
				if(Me.compareCookies_Request_Session(Me.idAuth, request, ses)) {
					Cookie newBrownie = Me.bakeBrownie(Integer.MAX_VALUE), brownie = Me.findCookie(Me.brownie, request);
					Cookie auth = Me.findCookie(Me.idAuth, request), newAuth = Me.idAuthGen(Integer.MAX_VALUE);

					saysomething = String.format("your [%s] cookie %s is now %s", brownie.getName(), brownie.getValue(), newBrownie.getValue());
					other = String.format("your [%s] cookie %s is now %s", auth.getName(), auth.getValue(), newAuth.getValue());

					brownie.setMaxAge(0);
					brownie.setValue(null);
					auth.setMaxAge(0);
					auth.setValue(null);

					response.addCookie(newBrownie);
					response.addCookie(newAuth);

					ses.setAttribute(Me.brownie, newBrownie);
					ses.setAttribute(Me.idAuth, newAuth);
				}
				else {
					System.out.println("d");
					response.sendRedirect(Me.errorHtml);
				}
		}
		else {
			System.out.println("e");
			response.sendRedirect(Me.errorHtml);
		}
	}
	else {
		System.out.println("f");
		response.sendRedirect(Me.errorHtml);
	}

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n");
      out.write("    <title>Garzon - Developer</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/real.css\">\n");
      out.write("    <script src=\"js/index.js\"></script>\n");
      out.write("\n");
      out.write("    <meta http-equiv=\"cache-control\" content=\"no-cache\" />\n");
      out.write("	<meta http-equiv=\"Cache-Control\" content=\"private, no-store\" />\n");
      out.write("\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"img/apple-icon-57x57.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"img/apple-icon-60x60.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"img/apple-icon-72x72.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"img/apple-icon-76x76.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"img/apple-icon-114x114.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"img/apple-icon-120x120.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"img/apple-icon-144x144.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"img/apple-icon-152x152.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"img/apple-icon-180x180.png\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"192x192\"  href=\"img/android-icon-192x192.png\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"img/favicon-32x32.png\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"96x96\" href=\"img/favicon-96x96.png\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"img/favicon-16x16.png\">\n");
      out.write("    <link rel=\"manifest\" href=\"img/manifest.json\">\n");
      out.write("    <meta name=\"msapplication-TileColor\" content=\"#ffffff\">\n");
      out.write("    <meta name=\"msapplication-TileImage\" content=\"img/ms-icon-144x144.png\">\n");
      out.write("    <meta name=\"theme-color\" content=\"#ffffff\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body id=\"index-body\">\n");
      out.write("    \n");
      out.write("    <header id=\"home\" class=\"container\">\n");
      out.write("        <h1 id=\"gismael-gzn\">gismael-gzn</h1>        \n");
      out.write("    </header>\n");
      out.write("\n");
      out.write("    <header class=\"contact\">\n");
      out.write("        <ul>\n");
      out.write("            <li> <img src=\"img/mail.png\" /> <a id=\"my-mail\" href=\"mailto:ggarzond1600@alumno.ipn.mx\"> ggarzond1600@alumno.ipn.mx</a> </li>\n");
      out.write("            <li> <a target=\"_blank\" href=\"https://github.com/gismael-gzn\"> <img src=\"img/GitHub_logo.png\" /> Github</a> </li>\n");
      out.write("            <li> <a target=\"_blank\" href=\"https://www.reddit.com/user/gismael\"> <img src=\"img/reddit-logo-16.png\" /> Reddit</a> </li>\n");
      out.write("            <li> <a target=\"_blank\" href=\"https://www.youtube.com/channel/UCFSb0zaA0Wl4cVwdQsYOilA\"> <img src=\"img/youtube-clipart-youtube-square-icons-1600x1600.png\" /> YouTube</a> </li>\n");
      out.write("        </ul>\n");
      out.write("    </header>\n");
      out.write("\n");
      out.write("    <nav id=\"navigation\" class=\"container\">\n");
      out.write("        <div class=\"close\"><a href=\"javascript:close_nav()\">X</a></div>\n");
      out.write("\n");
      out.write("        <details>\n");
      out.write("            <summary>Tema</summary>\n");
      out.write("            <em> <a class=\"theme-selector\" href=\"javascript:void(0)\">Day</a> </em> \n");
      out.write("            <em> <a class=\"theme-selector\" href=\"javascript:void(0)\">Night</a> </em> \n");
      out.write("        </details>\n");
      out.write("\n");
      out.write("        <details open>\n");
      out.write("            <summary>Navegar</summary>\n");
      out.write("            <ul class=\"index\">\n");
      out.write("                <li> <a onclick=\"close_nav();\" class=\"index-content\" href=\"#index-body\">Inicio</a> </li>\n");
      out.write("            </ul>\n");
      out.write("        </details>\n");
      out.write("\n");
      out.write("        <details open>\n");
      out.write("            <summary>Tabla de contenidos</summary>\n");
      out.write("            <ul class=\"index\">\n");
      out.write("               <li> <a class=\"index-content\" href=\"#Sobre-mi\" onclick=\"close_nav();\">Sobre mi</a> </li>\n");
      out.write("               <li> <a class=\"index-content\" href=\"#Formacion-academica\" onclick=\"close_nav();\">Formacion academica</a> </li>\n");
      out.write("               <li> <a class=\"index-content\" href=\"#Hobbies\" onclick=\"close_nav();\">Hobbies</a> </li>\n");
      out.write("               <li> <a class=\"index-content\" href=\"#Contactame\" onclick=\"close_nav();\">Cont&aacute;ctame</a> </li>\n");
      out.write("            </ul>\n");
      out.write("        </details>\n");
      out.write("\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <main class=\"container\">\n");
      out.write("\n");
      out.write("        <div id=\"mobile-menu\" class=\"container\">\n");
      out.write("            <a class=\"btn\" href=\"javascript:open_nav()\">Men&uacute;</a>\n");
      out.write("            <a class=\"btn\" href=\"javascript:open_main()\">Navegar a</a>\n");
      out.write("         </div>\n");
      out.write("\n");
      out.write("        <div id=\"main-menu\" class=\"container\">\n");
      out.write("            <div class=\"close\"><a href=\"javascript:close_main()\">X</a></div>\n");
      out.write("           <a class=\"btn\" href=\"");
      out.print( Me.Home );
      out.write("\">Home</a>\n");
      out.write("           <a class=\"btn\" href=\"");
      out.print( Me.Cryptography );
      out.write("\">Cryptography</a>\n");
      out.write("           <a class=\"btn\" href=\"");
      out.print( Me.Curriculum );
      out.write("\">Curriculum</a>\n");
      out.write("           <a class=\"btn\" href=\"https://youtu.be/ZZ5LpwO-An4?t=3\" target=\"_blank\">woop woop</a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <section id=\"main-content\" class=\"container\">\n");
      out.write("            \n");
      out.write("            <h2 id=\"Sobre-mi\" class=\"title\">Sobre mi</h2>\n");
      out.write("            \n");
      out.write("            \n");
      out.write("            <div class=\"info\">\n");
      out.write("                <img id=\"me\" class=\"inline-img\" src=\"img/2023-03-05 16.50.23.jpg\"/>\n");
      out.write("                <h3 id=\"Formacion-academica\">Formaci&oacute;n acad&eacute;mica</h3>\n");
      out.write("                <p>\n");
      out.write("                    Hola, me llamo <em> <b>Gerardo Ismael Garz&oacute;n Dom&iacute;nguez.</b> </em> Soy un estudiante de &uacute;ltimo a&ntilde;o en la carrera de Ingenier&iacute;a en Sistemas Computacionales en la Escuela Superior de C&oacute;mputo (ESCOM) del Instituto Polit&eacute;cnico Nacional (IPN), en M&eacute;xico, cursando actualmente el periodo acad&eacute;mico 2019-presente. Antes de ingresar a la ESCOM, curs&eacute; la carrera t&eacute;cnica en Construcci&oacute;n en el Centro de Estudios Cient&iacute;ficos y Tecnol&oacute;gicos (CECyT) 1 durante la generaci&oacute;n 2016-2019. Me apasiona la programaci&oacute;n y la tecnolog&iacute;a, y siempre estoy buscando nuevas oportunidades para aprender y enfrentar desaf&iacute;os en el campo.\n");
      out.write("                </p>\n");
      out.write("                <h3 id=\"Hobbies\">Hobbies</h3>\n");
      out.write("                <p>\n");
      out.write("                    Mis hobbies incluyen tocar la guitarra el&eacute;ctrica y aprender piano, lo que me permite expresar mi creatividad y relajarme a trav&eacute;s de la m&uacute;sica. Adem&aacute;s, disfruto hacer ejercicio, lo que me ayuda a mantener un equilibrio saludable entre mente y cuerpo. En mi tiempo libre, me gusta explorar pel&iacute;culas interesantes y surfear en internet para mantenerme actualizado y descubrir nuevos temas que me permitan expandir mi conocimiento y comprensi&oacute;n del mundo que me rodea. <br/>\n");
      out.write("                    Aqu&iacute; te muestro un par de clips m&iacute;os tocando la guitarra, aunque ya no suelo practicar por la escuela.\n");
      out.write("                    <iframe src=\"https://www.youtube.com/embed/s5BibsEMrac\" allowfullscreen></iframe>\n");
      out.write("                    <iframe src=\"https://www.youtube.com/embed/bXc7_m8Jy7Y\" allowfullscreen></iframe>\n");
      out.write("                </p>\n");
      out.write("                <h3 id=\"Contactame\">Cont&aacute;ctame</h3>\n");
      out.write("                <p>\n");
      out.write("                    Si deseas ponerse en contacto conmigo para hablar sobre proyectos, oportunidades de colaboraci&oacute;n o simplemente intercambiar ideas, no dudes en enviarme un correo electr&oacute;nico a <a href=\"mailto:ggarzond1600@alumno.ipn.mx\">ggarzond1600@alumno.ipn.mx</a> o con&eacute;ctate conmigo a trav&eacute;s de <a href=\"https://www.reddit.com/user/gismael\">Reddit</a>. Estoy siempre abierto a conocer gente nueva, aprender de sus experiencias y compartir conocimientos en el &aacute;mbito de la tecnolog&iacute;a y m&aacute;s all&aacute;.\n");
      out.write("                </p>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </section>\n");
      out.write("    </main>\n");
      out.write("\n");
      out.write("    <footer class=\"container\">\n");
      out.write("        <p>Footer: all rights reserved to Gerardo Ismael Garzon Dominguez</p>\n");
      out.write("    </footer>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
